ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += at86rf233
endif

ifneq (,$(filter eui_provider,$(USEMODULE)))
  USEMODULE += edbg_eui
endif

ifneq (,$(filter saul_default,$(usemodule)))
  usemodule += saul_gpio
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_sdcard
endif

# default to using fatfs on the external flash
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEMODULE += fatfs_vfs
  USEMODULE += mtd
endif
