include ../Makefile.tests_common

USEMODULE += ztimer_epoch
USEMODULE += ztimer_usec
USEMODULE += ztimer_msec
USEMODULE += ztimer_adjust_time
USEMODULE += atomic_utils
USEMODULE += embunit

include $(RIOTBASE)/Makefile.include
